version: '3.8'

services:
  gitlab-time-report:
    build:
      context: .
      dockerfile: Dockerfile
    image: gitlab-time-report:latest
    container_name: gitlab-time-report-app
    ports:
      - "80:80"
    restart: unless-stopped